services:
  postgres:
    image: postgres:17.2-alpine
    container_name: tournament-hub-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - tournament-hub
    volumes:
      - tournament-hub-db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432

  redis:
    image: redis:7-alpine
    container_name: tournament-hub-redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - tournament-hub-redis-data:/data
    networks:
      - tournament-hub
    restart: unless-stopped

volumes:
  tournament-hub-db:
  tournament-hub-redis-data:

networks:
  tournament-hub:
