export enum UserError {
  INCORRECT_CREDENTIALS = 'users.main.INCORRECT_CREDENTIALS',
  EMAIL_ALREADY_TAKEN = 'users.main.EMAIL_ALREADY_TAKEN',
  USERNAME_ALREADY_TAKEN = 'users.main.USERNAME_ALREADY_TAKEN',
}
