export enum TournamentError {
  CREATION_FAILED = 'tournaments.main.CREATION_FAILED',
  ALREADY_PARTICIPATING_IN_UNFINISHED_TOURNAMENT = 'tournaments.main.ALREADY_PARTICIPATING_IN_UNFINISHED_TOURNAMENT',
  PRIVATE_JOIN_REQUIRES_INVITE_TOKEN = 'tournaments.main.PRIVATE_JOIN_REQUIRES_INVITE_TOKEN',
  INVALID_INVITE_TOKEN = 'tournaments.main.INVALID_INVITE_TOKEN',
  CANNOT_JOIN_FINISHED_TOURNAMENT = 'tournaments.main.CANNOT_JOIN_FINISHED_TOURNAMENT',
}
