export enum TournamentError {
  CREATION_FAILED = 'tournaments.main.CREATION_FAILED',
  ALREADY_PARTICIPATING_IN_UNFINISHED_TOURNAMENT = 'tournaments.main.ALREADY_PARTICIPATING_IN_UNFINISHED_TOURNAMENT',
  PRIVATE_JOIN_REQUIRES_INVITE_TOKEN = 'tournaments.main.PRIVATE_JOIN_REQUIRES_INVITE_TOKEN',
  INVALID_INVITE_TOKEN = 'tournaments.main.INVALID_INVITE_TOKEN',
  CANNOT_JOIN_FINISHED_TOURNAMENT = 'tournaments.main.CANNOT_JOIN_FINISHED_TOURNAMENT',
  ONLY_OWNER_CAN_START_TOURNAMENT = 'tournaments.main.ONLY_OWNER_CAN_START_TOURNAMENT',
  TOURNAMENT_ALREADY_STARTED = 'tournaments.main.TOURNAMENT_ALREADY_STARTED',
  NOT_ENOUGH_PARTICIPANTS_TO_START = 'tournaments.main.NOT_ENOUGH_PARTICIPANTS_TO_START',
  OWNER_CANNOT_LEAVE_TOURNAMENT = 'tournaments.main.OWNER_CANNOT_LEAVE_TOURNAMENT',
  CANNOT_LEAVE_ACTIVE_TOURNAMENT = 'tournaments.main.CANNOT_LEAVE_ACTIVE_TOURNAMENT',
  CANNOT_SUBMIT_OUTSIDE_SUBMISSION_PHASE = 'tournaments.main.CANNOT_SUBMIT_OUTSIDE_SUBMISSION_PHASE',
  SUBMISSION_AUTHOR_IS_NOT_PARTICIPANT = 'tournaments.main.SUBMISSION_AUTHOR_IS_NOT_PARTICIPANT',
}
